<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'No. in order'     => '№ п/п',
    'Primary means'    => 'Основное средство',
    'Inventory number' => 'Инвентарный номер',
    'Date of acceptance for registration' => 'Дата принятия к учету',
    'State'            => 'Состояние',
    'Region'           => 'ИФО',
    'Storage'          => 'Место хранения',
    'Financially responsible person' => 'МОЛ',
    'Type'             => 'Тип',
    'Network name'     => 'Сетевое имя',
    'Operation system' => 'Операционная система',
    'MAC address'      => 'Сетевой адрес',
    'Serial number'    => 'Серийный номер',
    'Product number'   => 'Код продукта',
    'Model number'     => 'Номер модели',
    'Location'         => 'Место хранения',
];
