<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Date of acceptance for registration' => 'Дата принятия к учету',
    'Financially responsible person' => 'МОЛ',
    'Import: {comment}' => 'Импорт: {comment}',
    'Inventory number' => 'Инвентарный номер',
    'Location' => 'Место хранения',
    'Location: {location} ({region})' => 'Размещение:  {location} ({region})',
    'MAC address' => 'Сетевой адрес',
    'Model number' => 'Номер модели',
    'Network name' => 'Сетевое имя',
    'No. in order' => '№ п/п',
    'Operation system' => 'Операционная система',
    'Primary means' => 'Основное средство',
    'Product number' => 'Код продукта',
    'Region' => 'ИФО',
    'Serial number' => 'Серийный номер',
    'State' => 'Состояние',
    'Type' => 'Тип',
    '), Inventory number:{invent}, model: {model}, location: {location} ( {region} )' => '), Инвентарный номер:{invent}, модель: {model}, Размещение: {location} ( {region} )',
    'Moving: {date} (' => 'Перемещение: {date} (',
    'Skip all. Key column not found: ' => 'Всё пропущено. Отсутствуют ключевые поля: ',
];
