<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Additional Information' => 'Дополнительная информация',
    'Attribute filecsv is not set' => 'Атрибут filecsv не установлен',
    'CSV or XLS file' => 'Файл CSV или XLS',
    'Checked item(s): ' => 'Учтено оборудование: ',
    'Create Items' => 'Добавить оборудование',
    'File upload is not valid' => 'Загруженный файл неверный',
    'Import' => 'Импортировать',
    'Import Items' => 'Импорт оборудования',
    'Inventory QR-code' => 'Инвентарный QR-код',
    'Inventory number' => 'Инвентарный номер',
    'Item network name' => 'Сетевое имя',
    'Item type' => 'Тип оборудования',
    'Items' => 'Оборудование',
    'Items: Failed to add entry' => 'Оборудование: Не удалось добавить запись',
    'Items: Key field missing "invent", "serial", "model"' => 'Оборудование: Отсутсвуют ключевые поля: "invent", "serial", "model"',
    'Location' => 'Место размещения',
    'Location checked' => 'Место размещения проверено',
    'MAC address' => 'MAC адрес',
    'Model' => 'Модель',
    'Model number' => 'Номер модели',
    'Operating system' => 'Операционная система',
    'Print Items' => 'Печать этикеток',
    'Print selected labels' => 'Печать выбранных этикеток',
    'Product number' => 'Код оборудования',
    'Read {countRows} records.<br />Imported {countImported} Items.<br />Exists {countExists} Items.<br />Error read {countErrors} records.<br />{errors}' => 'Прочитано {countRows} записей.<br />Импортировано {countImported} оборудования.<br />Уже зарегистрировано {countExists} оборудования.<br />Не удалось обработать {countErrors} записей.<br />{errors}',
    'Region' => 'Подразделение',
    'Serial number' => 'Серийный номер',
    'Start checking' => 'Начать инвентаризацию',
    'State' => 'Состояние',
    'Total items checked' => 'Учтено',
    'Total items count' => 'Всего',
    'Update Items: {name}' => 'Изменение оборудования: {name}',
    'Model identifier' => 'Идентификатор модели',
];
