<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'All regions' => 'Все подразделения',
    'Create location' => 'Добавить место',
    'Error to create location "{location}"' => 'Ошибка создания размещения "{location}"',
    'Location' => 'Место размещения',
    'Location name' => 'Наименование места размещения',
    'Locations' => 'Места размещения',
    'Region ID' => 'Идентификатор подразделения',
    'Select location' => 'Выберите место',
    'The requested page does not exist.' => 'Запрошенная страница отсуствует',
    'Update Locations: {name}' => 'Изменение места: {name}',
    'Locations: Key field missing "location" and "region" :' => 'Размещение: Отсутсвуют ключевые поля "location" и "region" :',
];
