<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Create Model' => 'Добавить модель',
    'Migration: error add model: ' => 'Миграция: ошибка добавления модели: ',
    'Model name' => 'Название',
    'Model number' => 'Номер модели',
    'Models' => 'Модели',
    'Prodict number' => 'Код оборудования',
    'Select model' => 'Выберите модель',
    'Type identify' => 'Идентификатор типа',
    'Update Model: {name}' => 'Изменение модели {name}',
    'Models: Failed to add entry: ' => 'Модели: Невозможно доавить запись: ',
    'Models: Key field "model", "type" missing: ' => 'Модели: Ключевые поля "model", "type" отсуствуют: ',
];
