<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Comment' => 'Комментарии',
    'Create Moving' => 'Добавление перемещения',
    'Date cannot be less than {date}' => 'Дата не может быть меньше чем {date}',
    'Item ID' => 'Идентификатор оборудования',
    'Location ID' => 'Идентификатор места',
    'Moving date' => 'Дата перемещения',
    'Movings' => 'Перемещения',
    'Reset' => 'Сброс',
    'Search' => 'Поиск',
    'Status ID' => 'Идетификатор состояния',
    'The date cannot be less than {date}' => 'Дата не может быть меньше, чем {date}',
    'The date cannot be more than today' => 'Дата не может быть больше чем сегодя',
    'The date cannot be more than {date}' => 'Дата не может быть больше чем {date}',
    'Update Moving: {name}' => 'Изменение перемещения: {name}',
    'Дата не может быть меньше, чем {date}' => 'Дата не может быть меньше, чем {date}',
];
