<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Change password' => 'Смена пароля',
    'New password' => 'Новый пароль',
    'Old password' => 'Старый пароль',
    'Old password is incorrect.' => 'Старый пароль неправильный',
    'Password' => 'Пароль',
    'User name' => 'Имя пользователя',
    'You have successfully change your password.' => 'Вы успешно сменили свой пароль',
    'repeat password' => 'Повторите пароль',
    'Create user' => 'Добавление пользователя',
    'Create users' => 'Добавление пользователей',
    'Manage users' => 'Управление пользователями',
    'User {name} is created' => 'Пользователь {name} создан',
];
