language: php

before_script:
    # Start up a web server
    - php -S 127.0.0.1:8888 -t web >/dev/null 2>&1 &
    # Start up the webdriver
    - phantomjs --webdriver=4444 >/dev/null 2>&1 &
    # Install codeception
    - composer install --prefer-source

script:
    - vendor/bin/codecept run
